In [147]:
import camelot
import pandas as pd

In [117]:
tables = camelot.read_pdf('hplc.pdf')

In [118]:
tables

In [119]:
tables.export('foo.csv', f = 'csv', compress = True)

In [122]:
tables[0]

In [123]:
tables[0].df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,,Sample\nName,Name,Batch_No.,Vial,Inj,Inj.\nVol.\n(uL),Ch.\nNo.,Std\nWeight,Std_\nDilnFactor,Std_\nWC_LOD,Std_\nAvg_Area,Potency,Sample\nWeight,Dilution,Spl_wc\nLOD_Solv,Avgwt\n_wtml,Sample\nArea\n(µV*sec),Assay,Result\nId
1,1 2,Cefpodoxime Proxetil IP_1/1,sum,CDPNF18040,5 5,1 1,20.00,11,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,390029,695.178,18883
2,,Cefpodoxime Proxetil IP_1/2,sum,CDPNF18040,,,20.00,12,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,389827,694.819,18884
3,Mean,,,,,,,,,,,,,,,,,389928,695.0,

In [184]:
data = tables[0].df
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,,Sample\nName,Name,Batch_No.,Vial,Inj,Inj.\nVol.\n(uL),Ch.\nNo.,Std\nWeight,Std_\nDilnFactor,Std_\nWC_LOD,Std_\nAvg_Area,Potency,Sample\nWeight,Dilution,Spl_wc\nLOD_Solv,Avgwt\n_wtml,Sample\nArea\n(µV*sec),Assay,Result\nId
1,1 2,Cefpodoxime Proxetil IP_1/1,sum,CDPNF18040,5 5,1 1,20.00,11,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,390029,695.178,18883
2,,Cefpodoxime Proxetil IP_1/2,sum,CDPNF18040,,,20.00,12,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,389827,694.819,18884
3,Mean,,,,,,,,,,,,,,,,,389928,695.0,

In [185]:
class Sample:
  def __init__(self,sample_name, name, assay):
    self.sample_name = sample_name
    self.name = name
    self.assay = assay
    
  def get_sample_name(self):
    return self.sample_name

  def get_name(self):
    return self.name

  def get_assay(self):
    return self.assay

In [186]:
data = tables[0].df
rows = data.shape[0]
rows = rows-2
rows

2

In [187]:
data_list = []
row_index = 1
for i in range(len(tables)):
    
    data = tables[i].df
    
    while(row_index != rows):

        sample_obj = Sample(data[1][row_index], data[2][row_index], data[18][row_index])
        data_list.append(sample_obj)
        row_index = row_index + 1;
        
            
        print(sample_obj.get_name())
        print(sample_obj.get_sample_name())
        print(sample_obj.get_assay())

sum
Cefpodoxime Proxetil IP_1/1
695.178

In [188]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,,Sample\nName,Name,Batch_No.,Vial,Inj,Inj.\nVol.\n(uL),Ch.\nNo.,Std\nWeight,Std_\nDilnFactor,Std_\nWC_LOD,Std_\nAvg_Area,Potency,Sample\nWeight,Dilution,Spl_wc\nLOD_Solv,Avgwt\n_wtml,Sample\nArea\n(µV*sec),Assay,Result\nId
1,1 2,Cefpodoxime Proxetil IP_1/1,sum,CDPNF18040,5 5,1 1,20.00,11,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,390029,695.178,18883
2,,Cefpodoxime Proxetil IP_1/2,sum,CDPNF18040,,,20.00,12,50.010,0.00050,0.00000,418014,744.300,51.1300,2000.0000,2.29000,1.00000,389827,694.819,18884
3,Mean,,,,,,,,,,,,,,,,,389928,695.0,

In [148]:
import csv
HEADERS = next(csv.reader(open('foo.csv')))
print (HEADERS)

['', 'Sample\nName', 'Name', 'Batch_No.', 'Vial', 'Inj', 'Inj.\nVol.\n(uL)', 'Ch.\nNo.', 'Std\nWeight', 'Std_\nDilnFactor', 'Std_\nWC_LOD', 'Std_\nAvg_Area', 'Potency', 'Sample\nWeight', 'Dilution', 'Spl_wc\nLOD_Solv', 'Avgwt\n_wtml', 'Sample\nArea\n(ÂµV*sec)', 'Assay', 'Result\nId']

In [150]:
dframe = pd.DataFrame()
print(dframe)

Empty DataFrame
Columns: []
Index: []

In [189]:
# data_list = []
# row = 1
# for i in range(len(tables)):
    
#     data = tables[i].df
    
#     one = Sample(data[1][1], data[2][1], data[18][1])
#     two = Sample(data[1][2], data[2][2], data[18][2])
    
#     data_list.append(one)
#     data_list.append(two)
    
#     print(one.get_name())
#     print(one.get_sample_name())
#     print(one.get_assay())
#     print(data_list[0].get_name())